### ISSUE TITLE
Using latest datastax Cassandra breaks vertx deployment

### ISSUE THREAD

**Issue by krystianity** [englishtown/vertx-cassandra#12]
Setup is: 

<dependency>
            <groupId>com.englishtown.vertx</groupId>
            <artifactId>vertx-cassandra</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.datastax.cassandra</groupId>
            <artifactId>cassandra-driver-core</artifactId>
            <version>3.0.0-beta1</version>
        </dependency>
        <dependency>
            <groupId>com.datastax.cassandra</groupId>
            <artifactId>cassandra-driver-mapping</artifactId>
            <version>3.0.0-beta1</version>
        </dependency>

Causes:

Dec 09, 2015 3:47:14 PM io.vertx.core.Starter
SEVERE: Failed in deploying verticle
java.lang.AbstractMethodError: com.englishtown.vertx.cassandra.impl.Metrics$GaugeStateListener.onRegister(Lcom/datastax/driver/core/Cluster;)V
        at com.datastax.driver.core.Cluster.register(Cluster.java:449)
        at com.englishtown.vertx.cassandra.impl.Metrics.afterReconnect(Metrics.java:61)
        at com.englishtown.vertx.cassandra.impl.DefaultCassandraSession.reconnect(DefaultCassandraSession.java:156)
        at com.englishtown.vertx.cassandra.impl.DefaultCassandraSession.init(DefaultCassandraSession.java:101)
        at com.englishtown.vertx.cassandra.impl.DefaultCassandraSession.lambda$new$0(DefaultCassandraSession.java:46)
        at com.englishtown.vertx.cassandra.impl.JsonCassandraConfigurator.onReady(JsonCassandraConfigurator.java:100)
        at com.englishtown.vertx.cassandra.impl.DefaultCassandraSession.<init>(DefaultCassandraSession.java:41)
        at com.rewedigital.pels.Service.makeCassandraConnection(Service.java:141)
        at com.rewedigital.pels.Service.start(Service.java:66)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$169(DeploymentManager.java:407)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:314)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)

**Comment by chrisscha** [comment]
I got this same error tonight. Managed to fix it by upgrading my vertx-cassandra libraries to 3.2.0-SNAPSHOT

https://github.com/englishtown/vertx-cassandra

**Comment by krystianity** [comment]
@chrisscha you are right! 3.2.0-SNAPSHOT fixes the problem. ty for making me aware.
